StudentPal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('home.urls')),
    url(r'', include('userinfo.urls')),
    url(r'', include('schedule.urls')),
    url(r'^performance/', include('performance.urls')),
    url(r'^groups/', include('groups.urls'))
]

groups/urls.py
from django.conf.urls import url
from groups import views

urlpatterns = [
	url(r'^$', views.mygroups, name='my_groups'),
	url(r'^new$', views.newgroup, name='new_group'),
	url(r'^search$', views.searchgroups, name='search_groups'),
	url(r'^(?P<pk>\d+)/$', views.particulargroup, name='particular_group')
]

home/urls.py
from django.conf.urls import url
from home import views as home_views
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from performance import views as perf_views

urlpatterns = [
    url(r'^$', perf_views.home, name='homepage'),
    url(r'^login/$', auth_views.login, {'template_name': 'home/login.html'}, name='login'),
    url(r'^logout/$', home_views.mylogout, name='logout'),
    url(r'^signup/$', home_views.signup, name='signup'),
    #url(r'^test/$', home_views.test, name='test'),
]

groups/models.py
from django.db import models
from django.contrib.auth.models import User

class CustomGroup(models.Model):
    members = models.ManyToManyField(User, through='Invite', through_fields=('group', 'invitee'))
    name = models.CharField(max_length=50)
    description = models.TextField(default='')

    def __str__(self):
        return self.name

class Invite(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='senders')
    invitee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='invitees')
    group = models.ForeignKey(CustomGroup, on_delete=models.CASCADE, related_name='groups')
    is_accepted = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    is_requested = models.BooleanField(default=False)

    def __str__(self):
        return "%s's invitation sent to %s for joining the group '%s'" %(self.sender.username, self.invitee.username, self.group.name)

class FakeCourse(models.Model):
    name = models.CharField(max_length=20, default='')
    group = models.ForeignKey(CustomGroup, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "Course '%s' in the group '%s'" %(self.name, self.group.name)

groups/forms.py
from django import forms
from .models import FakeCourse

class new_group(forms.Form):
    name = forms.CharField(max_length=50)
    description = forms.CharField(widget=forms.Textarea)

    def clean(self):
        cleaned_data = super(new_group,self).clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')
        if not name:
            raise forms.ValidationError('This has to be filled')

class search_group(forms.Form):
    string = forms.CharField(max_length=50, label="Find a group ")

class new_course(forms.ModelForm):
    name = forms.CharField(max_length=20, label="Add a course")
    class Meta:
        model = FakeCourse
        fields = ['name']

groups/views.py
from django.shortcuts import render, redirect, get_object_or_404
from groups.models import Invite, CustomGroup
from django.contrib.auth.models import User
from groups.forms import *

def mygroups(request):
    if request.method == 'POST':
        user = User.objects.get(username=request.user)
        pending_invites = Invite.objects.filter(invitee=user, is_rejected=False, is_accepted=False)
        for invite in pending_invites:
            if "accept_"+str(invite.group.pk) in request.POST:
                invite.is_accepted=True
                invite.save()
            if "reject_"+str(invite.group.pk) in request.POST:
                invite.is_rejected=True
                invite.save()
        return redirect('my_groups')
    else:
        user = User.objects.get(username=request.user)
        accepted_invites = Invite.objects.filter(invitee=user, is_accepted=True)
        pending_invites = Invite.objects.filter(invitee=user, is_rejected=False, is_accepted=False)
        rejected_invites = Invite.objects.filter(invitee=user, is_rejected=True)
        search_form = search_group()
        return render(request, 'groups/mygroups.html', {'accepted_invites' : accepted_invites,
                                                        'pending_invites' : pending_invites,
                                                        'rejected_invites' : rejected_invites,
                                                        'search_form' : search_form})

def newgroup(request):
    if request.method == 'POST':
        form = new_group(request.POST)
        if form.is_valid:
            #form.save()
            user = User.objects.get(username=request.user)
            name = request.POST.get('name')
            description = request.POST.get('description')
            group = CustomGroup.objects.create(name=name, description=description)
            invite = Invite.objects.create(sender=user, invitee=user, group=group, is_accepted=True)
            return redirect('my_groups')
    else:
        form = new_group()
    return render(request, 'groups/newgroup.html', {'form' : form})

def searchgroups(request):
    if request.method == 'POST':
        form = search_group(request.POST)
        if form.is_valid:
            string = request.POST.get('string')
            groups = CustomGroup.objects.filter(name__contains=string)
            return render(request, 'groups/searchgroups.html', {'groups' : groups, 'string' : string})
    else:
        return redirect('my_groups')

def particulargroup(request, pk):
    if request.method == 'POST':
        form = new_course(request.POST)
        if form.is_valid():
            form.save()
            group = get_object_or_404(CustomGroup, pk=pk)
            name = request.POST.get('name')
            fc = FakeCourse.objects.create(group=group, name=name)
            group.fakecourse_set.add(fc)
            user = User.objects.get(username=request.user)
            accepted_invites = Invite.objects.filter(group=group, is_accepted=True)
            check = Invite.objects.filter(group=group, invitee=user, is_accepted=True)
            courses = group.fakecourse_set.all()
            form = new_course()
            return render(request, 'groups/particulargroup.html', {'accepted_invites' : accepted_invites, 'group' : group, 'check' : check, 'courses': courses, 'form' : form})
    else:
        user = User.objects.get(username=request.user)
        group = get_object_or_404(CustomGroup, pk=pk)
        accepted_invites = Invite.objects.filter(group=group, is_accepted=True)
        check = Invite.objects.filter(group=group, invitee=user, is_accepted=True)
        form = new_course()
        courses = group.fakecourse_set.all()
        return render(request, 'groups/particulargroup.html', {'accepted_invites' : accepted_invites, 'group' : group, 'check' : check, 'form' : form, 'courses': courses})

groups/templates/groups/addcourse.html
<!DOCTYPE html>
<html>
<title>Search result</title>
<body>
	{{ form.as_p }}
</body>
</html>

groups/templates/groups/mygroups.html
<!DOCTYPE html>
<html>
<title>My groups</title>
<body>
	<form method="post" action="{% url 'search_groups' %}">
		{% csrf_token %}
		{{ search_form.as_p }}
		<button type="submit">Search</button>
	</form>
	<h2>You're in the following groups:</h2>
	<ul>
		{% for invite in accepted_invites %}
			{% if invite.sender.username == invite.invitee.username %}
				<li><a href="{% url 'particular_group' invite.group.pk %}">{{ invite.group.name }}</a>. You created the group.</li>
			{% else %}
				<li><a href="{% url 'particular_group' invite.group.pk %}">{{ invite.group.name }}</a>. You were invited by <a href="{% url 'profileview' invite.sender.username %}">{{ invite.sender.username }}</a>.</li>
			{% endif %}
		{% empty %}
			<p>You're not in any group.</p>
		{% endfor %}
		<p><a href='new'>Create</a> a new group.</p>
	</ul>

	<h2>Pending invites:</h2>
	<ul>
		{% for invite in pending_invites %}
			<li>
				<form method="post">
					{% csrf_token %}
					<p>You're invited to the group <a href="{% url 'particular_group' invite.group.pk %}">{{ invite.group.name }}</a> by <a href="{% url 'profileview' invite.sender.username %}">{{ invite.sender.username }}</a>.
					<button type="submit" name="accept_{{ invite.group.pk }}">Accept</button>
					<button type="submit" name="reject_{{ invite.group.pk }}">Reject</button></p>
				</form>
			</li>
		{% empty %}
			<p>You don't have any pending invites.</p>
		{% endfor %}
	</ul>

	<h2>Rejected invites:</h2>
	<ul>
		{% for invite in rejected_invites %}
			<li>You rejected an invite to the group <a href="{% url 'particular_group' invite.group.pk %}">{{ invite.group.name }}</a> sent by <a href="{% url 'profileview' invite.sender.username %}">{{ invite.sender.username }}</a>.</li>
		{% empty %}
			<p>You did not reject any invites.</p>
		{% endfor %}
	</ul>
</body>
</html>

groups/templates/groups/newgroup.html
<!DOCTYPE html>
<html>
<title>New group</title>
<body>
	<h2>Create a new group</h2>
	<form method="post">
		{% csrf_token %}
		<table>
		{{ form }}
		</table>
		<button type="submit">Create group</button>
<!--
		<label for="id_name">Group name</label>
		<input type="text" id="id_name" name="name">
		<br><br>
		<label for="id_description">Description</label>
		<input type="text" id="id_description" name="description">
		<button type="submit">Create group</button>
-->
	</form>
</body>

groups/templates/groups/particulargroup.html
<!DOCTYPE html>
<html>
<title>{{ group.name }}</title>
<body>
	<h1>{{ group.name }}</h1>
	<h2>Group members</h2>
	<ol>
		{% for invite in accepted_invites %}
			<li>{{ invite.invitee.username }}</li>
		{% endfor %}
	</ol>
	{% if check %}
		You're a member of this group.
	{% else %}
		You're not a member.
	{% endif %}
	<br><br>Courses compared in this group are
	{% for course in courses %}
		{{ course.name }},
	{% endfor %}
	Make sure you have courses with similar course codes.<br><br>
	<form method="post">
		{% csrf_token %}
		<table>
			{% for field in form %}
			<tr>
				<td> {{ field.label_tag }} </td>
				<td> {{ field }} </td>
				<td> <button type="submit">Add</button> </td>
			</tr>
			{% endfor %}
		</table>
	</form>
</body>
</html>

groups/templates/groups/searchgroups.html
<!DOCTYPE html>
<html>
<title>Search result</title>
<body>
	<h3>Search results for '{{ string }}':</h3>
	<ul>
		{% for group in groups %}
			<li>{{ group.name }}</li>
		{% empty %}
			<p>No groups found</p>
		{% endfor %}
	</ul>
</body>
</html>