StudentPal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('home.urls')),
    url(r'', include('userinfo.urls')),
    url(r'', include('schedule.urls')),
    url(r'^performance/', include('performance.urls')),
    url(r'^groups/', include('groups.urls'))
]

home/urls.py
from django.conf.urls import url
from home import views as home_views
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from performance import views as perf_views

urlpatterns = [
    url(r'^$', perf_views.home, name='homepage'),
    url(r'^login/$', auth_views.login, {'template_name': 'home/login.html'}, name='login'),
    url(r'^logout/$', home_views.mylogout, name='logout'),
    url(r'^signup/$', home_views.signup, name='signup'),
    #url(r'^test/$', home_views.test, name='test'),
]

performance/urls.py
from django.conf.urls import url
from django.contrib import admin
from performance import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
	url(r'^courses/(?P<pk>\d+)/$', views.course_exams, name='course_exams'),
	url(r'^courses/(?P<pk>\d+)/new/$', views.new_exam, name='new_exam'),
    url(r'^courses/new_course/$', views.new_course, name='new_course'),
    url(r'^pdf/', views.some_view, name='some_view'),
    #url(r'^courses/pdf_prac/$',views.pdf_prac, name='pdf_prac'),
]

performance/models.py
## @file models.py
#  @author SYNTAX
#  @date 28 Oct 2017
#  
#  @brief This is a file conatining some classes using python.
#
#  It contains of two classes named Course, Exam
#  The arguments describe the type of functions described in the class.

## @package django.db
#  Model fields required for framing custom models are imported from here.
#
from django.db import models
## @package django.contrib.auth.models
#  User model is imported from here.
#
from django.contrib.auth.models import User
## @package django.contrib.core.validators
#  MaxValueValidator,MinValueValidator are imported from here.
#
from django.core.validators import MaxValueValidator, MinValueValidator
## class Course 
#
# maintains data related to courses of user
# name,instructor, exams,code are its parts
#
class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    code = models.CharField(max_length=20, default='')
    name = models.CharField(max_length=50, default='')
    teacher = models.CharField(max_length=50, default='')
    comment = models.TextField(default='')
    ## Used to identify courses by their names.
    #  @return course_code of the Course
    def __str__(self):
        return self.code
    ## Used to get no. of exams in the course
    # 
    #  @return no. of exams in it.
    def get_exams_count(self):
        return Exam.objects.filter(course=self).count()
    ## Used to get exams list as output
    # 
    #  @return list of exams in it.2
    def get_courses(self):
        return list(Exam.objects.filter(course=self))
    ## Used to get percentage in the course
    # 
    #  @return Percentage in the course calculated from exams conducted till now.
    def get_percent_till_now(self):
        if self.get_exams_count() != 0:
            exams = Exam.objects.filter(course=self)
            net_percent = 0
            net_weightage = 0
            for exam in exams:
                net_weightage += exam.weightage
                net_percent += exam.weightage*exam.get_percent()
            ans = (net_percent/net_weightage)
        else:
            ans = 0
        ans = round(ans, 2)
        return ans
    ## Used to get marks in the course
    # 
    #  @return Score in the course calculated from exams conducted till now.
    def get_score_till_now(self):
        if self.get_exams_count() != 0:
            exams = Exam.objects.filter(course=self)
            net_percent = 0
            net_weightage = 0
            for exam in exams:
                net_weightage += exam.weightage
                net_percent += exam.weightage*exam.get_percent()
            ans = (net_percentage)
        else:
            ans = 0
        ans = round(ans, 2)
        return ans
## class Exam 
#
# maintains data related to exams of a course
# name,weighatge,max_marks,marks_obt are its parts
class Exam(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=30,)
    weightage = models.PositiveSmallIntegerField(default=100)
    max_marks = models.PositiveSmallIntegerField(default=100)
    marks_obt = models.PositiveSmallIntegerField(default=0)
    comment = models.TextField(blank=True, default='')

    def __str__(self):
        return self.name
    ## Used to get percentage of marks
    # 
    #  @return percentage of marks in the exam.
    def get_percent(self):
        percent  = (self.marks_obt/self.max_marks)*100
        percent = round(percent, 2)
        return percent

home/forms.py
## @file forms.py
#  @author SYNTAX
#  @date 28 Oct 2017
#  
#  @brief This is a file conatining some classes using python.
#
#  It contains class named CustomUserCreationForm
#  The arguments describe the type of functions described in the class.
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UsernameField

## class CustomUserCreationForm
#
# It is a form used to create new user
#first_name,last_name,email etc. are its parts
class CustomUserCreationForm(UserCreationForm):

    first_name = forms.CharField(
        label=_("First name"),
        max_length=20,
        required=True
    )
    last_name = forms.CharField(
        label=_("Last name"),
        max_length=20,
        required=False
    )
    email = forms.EmailField(
        label=_("Email Address"),
        required=True,
        help_text=_("Your email address is used to send you notifications, performance reports and also in case of a password reset.")
    )
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=_("Enter a password that is easy to remember and hard to guess.")
    )

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "first_name", "last_name", "email")
        field_classes = {'username': UsernameField}
    ## Used to save new user data to database
    # 
    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user

home/views.py
## @file views.py
#  @author SYNTAX
#  @date 28 Oct 2017
#  
#  @brief This is a file conatining some functions using python.
#
#  It contains of two functions named homepage,signup etc.
#  The arguments describe the type of functions described in the class.

from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import logout
from django.contrib.auth.decorators import login_required
from home.forms import CustomUserCreationForm

## Function homepage
#  @return Redirects to home.html page
def homepage(request):
    return render(request, 'home/home.html')


## Function signup
#
#  @details It takes details of new user.
#  @return Redirects to signup.html page
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('homepage')
    else:
        form = CustomUserCreationForm()
    return render(request, 'home/signup.html', {'form': form})

## Function mylogout
#
#  @details It is requested when wanted to logout.
#  @return Redirects to logout.html page
def mylogout(request):
    if request.method == 'POST':
        return logout(request, template_name='home/logged_out.html')
    else:
        return render(request, 'home/logout.html')

performance/views.py
## @file views.py
#  @author SYNTAX
#  @date 28 Oct 2017
#  
#  @brief This is a file conatining some functions using python.
#
#  It contains of two functions named home,new_exam etc.
#  The arguments describe the type of functions described in the class.


## @package django.contrib.auth.models
from django.contrib.auth.models import User
## @package django.shortcuts
from django.shortcuts import render, redirect, get_object_or_404
from .models import Course, Exam
## @package reportlab
from reportlab.pdfgen import canvas
## @package django.http
from django.http import HttpResponse, HttpResponseNotFound
## @package io
from io import BytesIO
## @package django.db.models
from django.db.models import Sum
import os, subprocess
## @package django.core.files.storage
from django.core.files.storage import FileSystemStorage

## Function home
#
#  @details It stores courses in variable named 'courses'
#  @return Redirects to home.html page
def home(request):
    if request.user.is_authenticated:
        u = User.objects.get(username=request.user)
        courses = u.course_set.all()
        return render(request, 'performance/home.html', {'courses': courses})
    else:
        return render(request, 'home/home.html')

## Function course_exams
#
#  @details It stores courses in variable named 'courses'
#  @return Redirects to exams.html page
def course_exams(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'performance/exams.html', {'course': course})

## Function new_exam
#
#  @return Redirects to new_home.html page
def new_exam(request, pk):
    course = get_object_or_404(Course, pk=pk)

    if request.method == 'POST':
        name = request.POST['exam']
        weightage = request.POST['weightage']
        marks_obt = request.POST['marks_obt']
        max_marks = request.POST['max_marks']
        comment = request.POST['comment']


        user = User.objects.first()  #get the currently logged in user

        exam = Exam.objects.create(
            name=name,
            course=course,
            weightage=weightage,
            marks_obt=marks_obt,
            max_marks=max_marks,
            comment=comment,
        )

        exam.save()
        #comment.save()
        return redirect('course_exams', pk=course.pk)
    else:
        return render(request, 'performance/new_exam.html', {'course': course})

## Function new_course
#
#  @return Redirects to new_course.html page
def new_course(request):
    if request.method == 'POST':
        name = request.POST['course_name']
        code = request.POST['course_code']
        teacher = request.POST['prof']
        user = User.objects.get(username=request.user)
        course = user.course_set.create(
            name=name,
            teacher=teacher,
            code=code,
        )
        course.save()
        return redirect('home')
    return render(request, 'performance/new_course.html')


def som_view(request):
    subprocess.call('cd static/',shell=True)
    subprocess.call('pdflatex texfile',shell=True)
    response = HttpResponse(pdf, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'
    return response

def some_view(request):
    subprocess.call('cd static/',shell=True)
    subprocess.call('pdflatex texfile',shell=True)
    fs = FileSystemStorage()
    filename = 'texfile.pdf'
    if fs.exists(filename):
        with fs.open(filename) as pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'
            return response
    else:
        return HttpResponseNotFound('The requested pdf was not found in our server.')

performance/templates/performance/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
    <meta charset="utf-8">
    <title>{% block title %}Courses:){% endblock %}</title>
    {% block head %}
    {% endblock %}
  <style>
    #navbarr {
    font-family: 'Shadows Into Light', cursive;

    }
  </style>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body >
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbarr">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}" style="font-size:300%;";><b>StuDent Pal</b></a>
        <a href="{% url 'user_info' %}" style="font-size:200%; color:#80D343;">Info</a>
        <a href="{% url 'events' %}" style="font-size:200%; color:#80D343;">Events</a>
        <a href="{% url 'home' %}" style="font-size:200%; color:#80D343;">Performance</a>
        <a href="{% url 'logout' %}" style="font-size:200%; color:#80D343;">Logout</a>
      </div>
</nav>
    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
      {% block content2 %}
      {% endblock %}
  
  </body>
</html>

performance/templates/performance/exams.html
{% extends 'performance/base.html' %}


{% block title %}
  {{ course.name }} - {{ block.super }}
{% endblock %}


{% block head %}
<style>
.canvasjs-chart-credit {
   display: none;
}
#newco{margin-bottom:30px;
      background-color: #80D343;}
#newco2{margin-bottom:30px;
      background-color: #80D343;}


input[type=button] {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 16px 32px;
    text-decoration: none;
    margin: 4px 2px;
    cursor: pointer;
}


table {  
    color: #333;
    font-family: Helvetica, Arial, sans-serif;
    width: 100%; 
    border-collapse: 
    collapse; border-spacing: 0; 
    margin-bottom:50px;
}

td, th {  
    border: 1px solid transparent; 
    height: 50px; 
    transition: all 0.3s;
    text-align: center;  
}

th {  
    background: #030303  ;
    color: #F6FAF4;  
    font-weight: bold;
    text-align: center;
}

td {  
    background: #FAFAFA;
    text-align: center;
}
      
tr:nth-child(even) td { background: #F1F1F1; }   

      
tr:nth-child(odd) td { background: #FEFEFE; }  

tr td:hover { background: #D1D4CF; color: white; }  

</style>
{% endblock %}


{% block breadcrumb %}
  <a href="{% url 'home' %}">Courses</a>/
  {{ course.name }}</br>
{% endblock %}


{% block content %}
<form action="{% url 'new_exam' course.pk %}">
    <input type="submit" value="New Exam" style="height: 37px; width: 10%;" id="newco"/>
</form>

<script type="text/javascript">
  var totalscore = 0;
</script>

  <table border="1">
    <thead>
      <tr>
        <th><center>Exam</center></th>
        <th><center>weightage</center></th>
        <th><center>Marks obtainded</center></th>
        <th><center>Max marks</center></th>
        <th><center>% obtained</center></th>
        <th><center>net score till now</center></th>
        <th><center>Comment</center></th>
      </tr>
    </thead>
    <tbody>
      {% for exam in course.exam_set.all %}
        <tr>
          <td>{{exam.name}}</td>
          <td id='weightage_{{forloop.counter}}'>{{exam.weightage}}</td>
          <td>{{exam.marks_obt}}</td>
          <td>{{exam.max_marks}}</td>
          <td id='percent_obt_{{forloop.counter}}'>{{ exam.get_percent }}</td>
          <td id='till_now_{{forloop.counter}}'></td>
          <td>{{exam.comment}}</td>
          <script type="text/javascript">
            var weightage = parseInt(document.getElementById('weightage_{{forloop.counter}}').innerHTML);
            var percentage = parseInt(document.getElementById('percent_obt_{{forloop.counter}}').innerHTML);
            document.getElementById('till_now_{{forloop.counter}}').innerHTML= totalscore+weightage*percentage/100;
            totalscore = totalscore+weightage*percentage/100;
          </script>
        </tr>
      {% endfor %}
    </tbody>
  </table>

<!DOCTYPE html>
<html>
<head>

<script>

window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
  exportEnabled: true,
  animationEnabled: true,
  title:{
    text: "Your performance"
  },
  
  axisX: {
    title: "Exams",
    crosshair: {
      enabled: true,
      snapToDataPoint: true
    }
  },
  axisY: {
    title: "Marks",
    titleFontColor: "#020202",
    lineColor: "#020202",
    labelFontColor: "#020202",
    tickColor: "#020202",
    min: 10,
  },
  
  toolTip: {
    shared: true
  },
  legend: {
    cursor: "pointer",
    itemclick: toggleDataSeries,
  },
  data: [{
    type: "line",
    colour:"#020202",
    name: "% obtained",
    showInLegend: true,      
    yValueFormatString: "#,##0.# ",
    dataPoints: [
    {% for exam in course.exam_set.all %}
      { label: "{{ exam.name }}",  y: {% widthratio exam.marks_obt exam.max_marks 100 %} },
    {% endfor %}
    ]
  },
  ]
});
chart.render();
var chart3 = new CanvasJS.Chart("chartContainer3", {
  theme: "light1", // "light1", "light2", "dark1", "dark2"
  exportEnabled: true,
  animationEnabled: true,
  title: {
    text: "Weightage of each exam till now"
  },
  data: [{
    type: "pie",
    startAngle: 25,
    toolTipContent: "<b>{label}</b>: {y}%",
    showInLegend: "true",
    legendText: "{label}",
    indexLabelFontSize: 16,
    indexLabel: "{label} - {y}%",
    dataPoints: [
    {% for exam in course.exam_set.all %}
      { y: {% widthratio exam.weightage exam.max_marks exam.marks_obt %}, label: "{{exam.name}}" },
    {% endfor %}
    ]
  }]
});
chart3.render();

function toggleDataSeries(e) {
  if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
    e.dataSeries.visible = false;
  } else {
    e.dataSeries.visible = true;
  }
  e.chart.render();
}

}
</script>
</head>
<body>
  <div id="chartContainer3" style="height: 370px; width: 100%;"></div>
  </br></br></br></br>

<div id="chartContainer" style="height: 370px; width: 100%;"></div></br></br></br></br>

<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</body>
</html>
{% endblock %}

performance/templates/performance/home.html
{% extends 'performance/base.html' %}

{% block head %}
<style>
.canvasjs-chart-credit {
   display: none;
}
#newco{margin-bottom:30px;
      background-color: #80D343;}


input[type=button] {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 16px 32px;
    text-decoration: none;
    margin: 4px 2px;
    cursor: pointer;
}


table {
    color: #333;
    font-family: Helvetica, Arial, sans-serif;
    width: 100%;
    border-collapse:
    collapse; border-spacing: 0;
    margin-bottom:50px;
}

td, th {
    border: 1px solid transparent;
    height: 50px;
    transition: all 0.3s;
    text-align: center;
}

th {
    background: #030303  ;
    color: #F6FAF4;
    font-weight: bold;
    text-align: center;
}

td {
    background: #FAFAFA;
    text-align: center;
}

tr:nth-child(even) td { background: #F1F1F1; }


tr:nth-child(odd) td { background: #FEFEFE; }

tr td:hover { background: #D1D4CF; color: white; }

</style>
{% endblock %}


{% block breadcrumb %}

  <li>Courses</li>
{% endblock %}

{% block content %}

<form action="{% url 'new_course' %}" background-color="#80D343;">
    <input type="submit" value="New Course" style="height: 37px; width: 10%;" id="newco"/>
</form>

 <center>
  <table border="1">
    <thead>
      <tr>
        <th><center>Course</center></th>
        <th><center>Prof. name</center><center></th>
        <th><center>No.of exams over</center></th>
        <th><center>Net % till now</center></th>
      </tr>
    </thead>
    <tbody>
      {% for course in courses %}
        <tr>
          <td>
            <a href="{% url 'course_exams' course.pk %}">{{ course.name }}</a>
          </td>
          <td >{{ course.teacher }}</td>
          <td>{{ course.get_exams_count }}</td>
          <td>{{ course.get_percent_till_now }}</td>

<script type="text/javascript">
  var cars="{{course.get_perc}}";
  var numb=0;
  var i;
  for (i = 0; i < cars.length; i++) {
    numb += cars[i].{{ weightage }};
}
document.getElementById("sum_{{forloop.counter}}").innerHTML = cars;
</script>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</center>




<head>
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
  animationEnabled: true,
  exportEnabled: true,
  theme: "light1", // "light1", "light2", "dark1", "dark2"
  title:{
    text: "% in respective courses"
  },
  data: [{
    type: "bar", //change type to bar, line, area, pie, etc
    //indexLabel: "{y}", //Shows y value on all Data Points
    indexLabelFontColor: "#5A5757",
    indexLabelPlacement: "outside",
    dataPoints: [
    {% for course in courses %}
      { label: "{{ course.name }}", y: {% widthratio course.get_percent_till_now 100 100 %} },
    {% endfor %}
    ]
  }]
});
chart.render();

}
</script>

<body>
  <center>
<div id="chartContainer" style="height: 370px; width: 80%;"></div>
 </center>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</body>
</html>
{% endblock %}

performance/templates/performance/new_course.html
{% extends 'performance/base.html' %}

{% block title %}New Course{% endblock %}
{% block head %}
<style>
  #id_course_name {margin-bottom:30px;}
  #id_course_code {margin-bottom:30px;}
  #id_prof {margin-bottom:30px;}
</style>

{% endblock %}

{% block breadcrumb %}
  <a href="{% url 'home' %}">Courses</a>/
  New Course
{% endblock %}

{% block content %}

  <form method="post">
    {% csrf_token %}
  <div class="form-group">
      <input type="text" class="form-control" id="id_course_name" name="course_name" placeholder="Course name" style="width: 300px;height: 60px;">
      <input type="text" class="form-control" id="id_course_code" name="course_code" placeholder="Course code" style="width: 300px;height: 60px;">
      <input type="text" class="form-control" id="id_prof" name="prof" placeholder="Instructor name" style="height: 60px;width: 60%;">    
    <button type="submit" class="btn btn-success">Post</button>

  </div>
  </form>
{% endblock %}

performance/templates/performance/new_exam.html
{% extends 'performance/base.html' %}

{% block title %}New Exam{% endblock %}


{% block head %}
<style>
  #id_exam {margin-bottom:30px;}
  #id_weight {margin-bottom:30px;margin-right:20px;}
  #id_marks_obt {margin-bottom:30px;margin-right:20px;}
  #id_max_marks {margin-bottom:30px;}
  #id_comment {margin-bottom:30px;}
</style>
{% endblock %}

{% block breadcrumb %}
  <a href="{% url 'home' %}">Courses</a> / 
  <a href="{% url 'course_exams' course.pk %}">{{ course.code }}</a> /
  New exam
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <input type="text" class="form-control" id="id_exam" name="exam" placeholder="Exam name" style="width: 300px;height: 60px;">

      <input type="integer" id="id_weight" name="weightage" placeholder=" Weightage" style="width: 30%;height: 60px;">


      <input type="integer" id="id_marks_obt" name="marks_obt" placeholder=" Marks obatined" style="width: 30%;height: 60px;">


      <input type="integer" id="id_max_marks" name="max_marks" placeholder=" Maximum marks" style="width: 30%;height: 60px;">


      <input type="text" class="form-control" id="id_comment" name="comment" placeholder="Comment" style="height: 60px;">

    </div>
    <button type="submit" class="btn btn-success">Submit</button>
  </form>
{% endblock %}